### ISSUE TITLE
any doclite news

### ISSUE THREAD

**Issue by REDAL** [dwgebler/doclite#20]
Hi @dwgebler 

grateful for y ou library, and wondering is there is any news or coming features ?

kindest regards

**Comment by dwgebler** [comment]
@REDAL I added full text search capability and joining collections in the last release, only thing in progress is a new feature to allow encryption of the database on-disk. But if people want new features, they need to give feedback and tell me what they're finding useful, any issues they're having, what they'd like to see in future. Otherwise I won't know what new features people might need. Thanks.

**Comment by REDAL** [comment]
@dwgebler Indeed,
I find it very useful, especially since it takes SQLite as the backend, which gives it a more robust backend than other PHP flat databases.

for ideas, I have a bunch of ideas, but since I didn't explored all docite, may you are already implemented some of it, but if it is ok, I'll share them with you any way.

right, encryption will be beneficial, it will add another level of security to data.

now I use it, with composer, if you make it standalone, just include one file, and it takes care of all dependencies.

also, I have an idea, if I can discuss it with you in private !

**Comment by dwgebler** [comment]
You can email me info@doclite.co.uk thanls
